language: cpp
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libsdl2-dev libglib2.0-dev libopenal-dev gettext libfreetype6-dev libxi-dev libpng12-dev zlib1g-dev libmpeg2-4-dev zip
script: ./bootstrap.sh && ./configure && make distcheck
